export const cryptoData = [
  {
      image: '../img/bitcoin.png',
      name: 'Bitcoin',
      price: '$22,272',
      change: '-1.16%',
      marketCap: '$434B',
  },
  {
      image: '../img/Ethereum.png',
      name: 'Ethereum',
      price: '$3,200',
      change: '-1.16%',
      marketCap: '$380B',
  },
  {
    image: '../img/Tether.png',
    name: 'Tether',
    price: '$1,23.00',
    change: '1.00%',
    marketCap: '$120B',
},
{
  image: '../img/BNB.png',
  name: 'BNB',
  price: '$237.70',
  change: '-0.36%',
  marketCap: '$36B',
},
{
  image: '../img/Cardano.png',
  name: 'Cardano',
  price: '$1.00',
  change: '0.03%',
  marketCap: '$13B',
},
{
  image: '../img/Solana.png',
  name: 'Solana',
  price: '$0.33',
  change: '2.03%',
  marketCap: '$1B',
},
{
  image: '../img/Dogecoin.png',
  name: 'Dogecoin',
  price: '$33.48',
  change: '-3.23%',
  marketCap: '$32B',
},
{
  image: '../img/XRP.png',
  name: 'XRP',
  price: '$23.33',
  change: '23.03%',
  marketCap: '$133B',
},
{
  image: '../img/Chainlink.png',
  name: 'Chainlink ',
  price: '$232.43',
  change: '5.00%',
  marketCap: '$122B',
},
{
  image: '../img/Litecoin.png',
  name: 'Litecoin',
  price: '$0.33',
  change: '2.03%',
  marketCap: '$1B',
},
{
  image: '../img/Stellar.png',
  name: 'Stellar',
  price: '$2.47',
  change: '-32.03%',
  marketCap: '$22B',
},
{
  image: '../img/Ethereum Classic.png',
  name: 'ETC',
  price: '$0.30',
  change: '-23.03%',
  marketCap: '$23B',
},
{
  image: '../img/Theta.png',
  name: 'Theta ',
  price: '$2.83',
  change: '-1.40%',
  marketCap: '$10B',
},
{
  image: '../img/VeChain.png',
  name: 'VeChain',
  price: '$44.56',
  change: '80.03%',
  marketCap: '$85B',
},
{
  image: '../img/Tron.png',
  name: 'Tron ',
  price: '$29.33',
  change: '17.03%',
  marketCap: '$75B',
},
{
  image: '../img/Monero.png',
  name: 'Monero ',
  price: '$9.33',
  change: '-17.03%',
  marketCap: '$55B',
},
{
  image: '../img/EOS.png',
  name: 'EOS',
  price: '$29.33',
  change: '17.03%',
  marketCap: '$75B',
},
{
  image: '../img/PancakeSwap.png',
  name: 'PancakeSwap ',
  price: '$229.33',
  change: '67.03%',
  marketCap: '$165B',
},
{
  image: '../img/Algorand.png',
  name: 'Algorand',
  price: '$40.15',
  change: '-47.03%',
  marketCap: '$32B',
},
{
  image: '../img/NEO.png',
  name: 'NEO ',
  price: '$829.64',
  change: '87.03%',
  marketCap: '$15B',
},
{
  image: '../img/Ark.png',
  name: 'Ark ',
  price: '$0.64',
  change: '-45.03%',
  marketCap: '$15M',
},
{
  image: '../img/Enjin Coin.png',
  name: 'Enjin Coin ',
  price: '$109.64',
  change: '9.33%',
  marketCap: '$150M',
},
{
  image: '../img/Zilliqa.png',
  name: 'Zilliqa',
  price: '$210.00',
  change: '20.24%',
  marketCap: '$156M',
},
{
  image: '../img/Hedera Hashgraph.png',
  name: 'HBAR',
  price: '$00.99',
  change: '-43.00%',
  marketCap: '$2M',
},
{
  image: '../img/Cosmos.png',
  name: 'Cosmos ',
  price: '$0.01',
  change: '99.00%',
  marketCap: '$5M',
},
];